version: '3'

services:
  postgres:
    image: postgres:15
    shm_size: 1g
    restart: always
    user: 1002:1003
    environment:
      - TZ=GMT+3
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=stack_overflow
    ports:
      - 54320:5432
    volumes:
      - ./load_data/init_scripts:/docker-entrypoint-initdb.d/
      - ./pg_data:/var/lib/postgresql/data/
      - /etc/passwd:/etc/passwd/:ro
      - /var/run/postgresql:/var/run/postgresql/:ro
